name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: SalvaCarsi/github_action_test@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Removes old tags
      run: |
        chmod +x ./scripts/remove_old_tags.sh
        ./scripts/remove_old_tags.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
